### ISSUE TITLE
Doesn't work with uppercase char in startRegionWord

### ISSUE THREAD

**Issue by Mixerito** [thehogfather/brackets-custom-region-code-folding#7] opened 2015-10-06 02:59 UTC
When some uppercase character is used in startRegionWord and comment happens to be unindented (no whitespaces before the comment token), then folding doesn't work.

In that case line 38 in region-fold.js:
<b>(token.start + token.string.toLowerCase().indexOf(startWord)) : -1;</b>
simplifies to work as:
<b>(token.start + -1) : -1;</b>
When the line starts with comment (no whitespaces before), it simplifies to:
<b>(0 + -1) : -1;</b>

So the condition on line 42 is always false then.

Changing line 38 to:
<b>(token.start + token.string.toLowerCase().indexOf(startWord.toLowerCase())) : -1;</b>
helps to solve this issue.

**Comment by thehogfather** [comment] 2015-10-31 00:58
Hi @Mixerito could you submit a pull request for this?

**Comment by thehogfather** [comment] 2015-11-16 21:04
@Mixerito I am unable to reproduce this issue. Also, I am a little baffled as to why this should be the case since the regex used to match the keywords should ignore case. If you are able to give a specific example of how to reproduce this issue please so that. 

For now I will close the issue.
Thanks

**Closed as completed by thehogfather** 2015-11-16 21:04 UTC
